// Expresses the data required to create an user;
// You don't need the ID because it should be generated by the database
// You also don't need optionals with default values
export class CreateUserDTO {
	userName: string;
}
